### ISSUE TITLE
Recipe book not filled correct

### ISSUE THREAD

**Issue by Cr4fter-15** [florian-berger/indestructible-tools#1]
Every item I can craft is listed in the recipe book. But the items added by your mod are only displayed in the recipe book once they have been crafted.

The recipes should be displayed when I have the required items.

**Comment by florian-berger** [comment]
Hey,

thanks for reporting. I was able to reproduce the described behavior. I will take a look at it later. Hope you enjoy it anyway.

**Comment by florian-berger** [comment]
The issue was resolved in pull request #2. A new version will be available at CurseForge soon
