### ISSUE TITLE
[1.19] Crash when opening chest

### ISSUE THREAD

**Issue by Baggytrousers27** [florian-berger/indestructible-tools#9]
Forge 41.0.109
indestructibletools-2022.2

Started a new world, went to right click on a spawn chest and immediately crashed with this error:

Exception caught during firing event: 'net.minecraft.world.entity.player.Player net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock.getPlayer()

[crashlog](https://github.com/florian-berger/indestructible-tools/files/9172997/crash-2022-07-23_13.12.28-client.txt)

**Comment by florian-berger** [comment]
Hey,

thanks for reporting the issue. I was able to reproduce it.

~Do you need a fix for 1.19 or is 1.19.1 also OK?~
I will upload a fix very soon.
